### ISSUE TITLE
SDK was not ready in 10000 miliseconds

### ISSUE THREAD

**Issue by SO-ashusrivastava** [splitio/dotnet-client#104]
I am receiving **SDK was not ready in 10000 miliseconds** exception while making connection to split
I am using  **splitclient.BlockUntilReady(10000)**;

Increasing readyTimeout to 15000 ms did not resolve the issue

This is happening intermittently, I am not sure it is timeout or any other thing causing this issue.

Kindly, let me know what can be the resolution here?

**Comment by hbqdev** [comment]
Hi @SO-ashusrivastava 

If the issue happens intermittently, this maybe related to your networking/environment. Are you running behind any firewall?

Regards,
Tin Tran

**Comment by SO-ashusrivastava** [comment]
Hi @hbqdev

I've checked and found that ther is no outbound friewall from our network.

Please note that this issue occured very frequently on dates of 13-14-15 November.

Kindly let me know your insight on this.

Thanks,
Ashu

**Comment by SO-ashusrivastava** [comment]
Anyone? We need your help!

**Comment by sanzmauro** [comment]
hi @SO-ashusrivastava, can you share with us how you are initializing the sdk?

A few question to understand the context:
- Which version are you using? 
- Target version of your project.
- Can you enable sdk logs? Debug level 
- Are you instantiating the SDK once as a singleton and reusing it? 

Regards,
Mauro

**Comment by sanzmauro** [comment]
@SO-ashusrivastava ping 😄

**Comment by SO-ashusrivastava** [comment]
Hi @sanzmauro ,

We are initializing the sdk as 

`var configurationOptions = new ConfigurationOptions
                {
                    ReadTimeout = 15000,
                    ConnectionTimeout = 15000,
                    StreamingEnabled = true,
                    IPAddressesEnabled = false
                };
                if (splitClient == null)
                {
                    var factory = new SplitFactory(apiKey, configurationOptions);
                    splitClient = factory.Client();
                    try
                    {
                        splitClient.BlockUntilReady(readyTimeout);
                    }
                    catch
                    {
                        throw;
                    }
                }`

Please find below answers to your questions:

Which version are you using? - **7.2.1**
Target framework of your project. - **4.8**
Can you enable sdk logs? Debug level - I'll try it
Are you instantiating the SDK once as a singleton and reusing it? - **YES**

Looking forward for your response.

Thanks,
Ashu

**Comment by SO-ashusrivastava** [comment]
Anyone? We need your help!
@sanzmauro @hbqdev

**Comment by hbqdev** [comment]
Hi @SO-ashusrivastava 
Since haven't heard from you in awhile on this issue, we will close it for now. If you still require assistant in the future, you can open a new issue or we encourage you to send an email to support@split.io for better support.

Regards,
