### ISSUE TITLE
Support for Microsoft.FeatureManagement

### ISSUE THREAD

**Issue by JeffryGonzalez** [splitio/dotnet-client#111]
Hi! I'm evaluating this for a company I do work/training for. I've looked but I'm not finding if there is any support for hooking into the Microsoft.FeatureManagement package (like Azure does) here: https://learn.microsoft.com/en-us/azure/azure-app-configuration/use-feature-flags-dotnet-core?tabs=core5x

Would this be possible if it doesn't exist already?

**Comment by hbqdev** [comment]
Hi @JeffryGonzalez 

This is currently not yet supported and we have filed a feature request to our product team.

We will close this issue for now.

Regards,
