### ISSUE TITLE
Setting treatment percentage of traffic in the yml file

### ISSUE THREAD

**Issue by fmotas** [splitio/dotnet-client#88]
Hello,

I'm creating this issue because my team need to set the yml file for cases when split.io is off, but some of our splits have treatments with specific percentage, but currently it is not possible to be set using the dotnet-client sdk, so I raised a PR implementing this feature, can you please take a look that?

This is the PR: https://github.com/splitio/dotnet-client/pull/87

Thank you very much!

**Comment by sanzmauro** [comment]
Hi @fmotas,

From our side we want to better understand why do you need those changes before proceed, so if you can provide us more context about how you are using the sdk and more detail about limitation/problems that you are having today.

Thanks in advance,
Mauro

**Comment by fmotas** [comment]
Hey @sanzmauro,

We have some feature flags configured to be `on` for 40% of the traffic and `off` for 60% of the traffic, it works fine if split.io is online and we can ping your servers, but if you are down and we need to use the localhost yml file to grab the settings for our feature flags, we can't have the same configuration, we only have the option of setting the feature flag to be `on` or `off`, and that is why I raised that PR to allow us to have the flexibility of adjusting the feature behavior based on traffic.

**Comment by fmotas** [comment]
Hello @sanzmauro,

do you need any extra info?

**Comment by fmotas** [comment]
Hello @sanzmauro, any news?

**Comment by sanzmauro** [comment]
Hi @fmotas i am going to close this issue. If you require any further information, feel free to reopen it. 😄 

Best,
Mauro
