### ISSUE TITLE
Passing split logging messages to a custom ILogger instance is very confusing

### ISSUE THREAD

**Issue by jerryk414** [splitio/dotnet-client#91]
There's alot to unravel to describe these difficulties. But I believe that the basic problems are as follows:
1) `ISplitLogger` is not DI'd
2) `ISplitClient` is not DI'd
3) `ISplitClient` does not pass it's logger along to it's children
4) `ISplitFactory` does not provide a method for defining a custom `ISplitLogger` when creating an `ISplitClient`

In order to help better understand what i'm trying to describe, here's the scenario I found myself in.

After experiencing some sporadic issues with Split only occurring when deployed, I wanted to get debug logs to see if there were any clues. My app uses a custom `Microsoft.Extensions.Logging.ILogger` implementation to handle pushing logging messages where we need them to go and for handling logging levels and all that - logging messages that don't use that custom `ILogger` simply do not write and cannot be viewed. After going through dozens of trials and reading through the code several times, I found that I needed to do the following to get all of this to work.

1) I needed to create a fake DI container for all of my dependencies that the ILogger relies on to be created
2) I needed to add my own implementation of `ILoggerFactory` that returns the `ILogger` defined above
3) I needed to call `SplitLoggerFactoryExtensions.AddSplitLogs()` to setup my custom `ILoggerFactory` as the static one to use

Only then could I create the real DI container, and use SplitFactory to create and register a singleton instance of ISplitClient. It just doesn't integrate well with DI, more specifically the ILogger - everything else seems to be pretty self-contained and thus not an issue.

So.. i'll just go one-by-one here to describe the problems as I see them since it's alot to unravel.

#### `ISplitLogger` is not DI'd
I can understand why not everything is DI'able. But the problem here is that, when using a custom logger, in order to get split's library to output logs using that custom logger, it is a huge hassle, and not easy to figure out. You would assume that just providing your own implementation of `Microsoft.Extensions.Logging.ILogger` in a DI container would be enough as it is with most libraries, but that is not the case.

Because loggers are creating statically and use a static `ILoggerFactory` to generate the logger, in order to force it to use your logger, you must provide your own `ILoggerFactory` AND you must register it as "THE" logger factory that split will use by using `SplitLoggerFactoryExtensions.AddSplitLogs()`. This also MUST be done prior to the `ISplitClient` instance being generated.

#### `ISplitClient` is not DI'd
Again, I can understand why this may need to be available in a non-DI manner, but for this one in particular, I really do feel as though a DI'able implementation of `ISplitClient` (or really an implementation of a provider that inspects the config to determine what implementation to use) could easily be made, and options can be defined via the `IOptions` interface. The problem with it not being DI'd is that for apps using DI that require an `ISplitClient`, you really can only create one on demand as needed, or inject a singleton for the entire app.

#### `ISplitClient` does not pass it's logger along to it's children
So this is just confusing and doesn't make sense. If an instance of `ISplitClient` is created with an instance of `ISplitLogger`, that instance should be used for all child dependencies. It's not necessarily a problem as it is right now, but the changes that would need to be made to support the other problems would make this problem surface as well.

#### `ISplitFactory` does not provide a method for defining a custom `ISplitLogger` when creating an `ISplitClient`
This could easily be a workaround solution - just update the ISplitFactory.Client() method to have an optional ISplitLogger parameter that gets passed along.

But really, if ISplitClient was DI'd and it's resolver referenced SplitFactory.Create, it should pass along the registered ILogger along to be used as the `ISplitLogger`.

**Comment by chillaq** [comment]
Hi @jerryk414 , I can check internally, any reason why you need to have ISplitLogger instance exist in all child classes?

**Comment by chillaq** [comment]
Hi @jerryk414 , we released version 7.1.0 to support exposing the ILogger interface
